### ISSUE TITLE
A problemo when playing a second game in speed run branch

### ISSUE THREAD

**Issue by LouayArafa** [LouayArafa/Ballin#1]
after completing the first game and pressing "play again", the main menu buttons will not work anymore. **too lazy to check why so good luck with that.**

**Comment by savian-delmo** [comment]
“The wrath of God is revealed from heaven against all ungodliness and unrighteousness of men, who by their unrighteousness suppress the truth”

**Comment by LouayArafa** [comment]
YA3TIK YA3TIK
